### ISSUE TITLE
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by stewest** [hail2u/node-csswring#91]
We just 'npm install'd - tried to run our gulp and get this:

> gulp "compile"

..../node_modules/csswring/index.js:90
  let c = `#${r1}${r2}${g1}${g2}${b1}${b2}`;
  ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/www/kendris_com/public_html/gulpfile.js:40:21)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)

**Comment by hail2u** [comment]
I think your Node.js is too old. Both latest (v9.5.0) and LTE (v8.9.4) works fine on my machine. Try upgrading Node.js.

**Comment by stewest** [comment]
Yes, thank you. It was our node version.
