### ISSUE TITLE
error in module.exports

### ISSUE THREAD

**Issue by aribet** [hail2u/node-csswring#92]
Hello, this line caused an error in my task gulp, I deleted it and it works. Check.

https://github.com/hail2u/node-csswring/blob/4f6467b9c8a127191fb0f8af654b78932725cdc6/index.js#L569

this is the error:
```
$ gulp css
...\node_modules\csswring\index.js:569
    ...options
    ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\wamp\www\Advision_WP_02\wpa_advision\wp-content\themes\advision_wp\gulpfile.js:5:18)
```

**Comment by hail2u** [comment]
You should upgrade Node.js to LTS or latest.
